steps:
  - name: 'docker/compose:1.19.0'
    args: [ '-f', 'docker/docker-compose.yml', 'up', '-d' ]
  - name: 'maven:3-openjdk-11'
    entrypoint: 'mvn'
    args: ['install']
    env:
      - 'MONGO_HOST=mongo'

- name: gcr.io/cloud-builders/docker
  args:
    - run
    - '--privileged'
    - 'linuxkit/binfmt:v0.7'
  id: initialize-qemu
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - buildx
  - create
  - '--name'
  - mybuilder

- name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - use
      - mybuilder
    id: select-builder
- name: gcr.io/cloud-builders/docker
  args:
    - buildx
    - inspect
    - '--bootstrap'
  id: show-target-build-platforms
- name: gcr.io/cloud-builders/docker
  args:
    - buildx
    - build
    - '--platform'
    - 'linux/amd64'
    - '-t'
    - 'eu.gcr.io/$PROJECT_ID/whakaoko'
    - '--push'
    - .
  id: build-multi-architecture-container-image
