steps:
  - name: docker
    args:
    - docker
    - run
    - '--privileged'
    - 'linuxkit/binfmt:v0.7'
    id: initialize-qemu
  - name: 'docker'
    args:
    - docker
    - exec
    - COPY
    - '----from=docker/buildx-bin:latest'
    - /buildx
    - /usr/libexec/docker/cli-plugins/docker-buildx
  - name: 'docker'
    args:
    - docker
    - buildx
    - create
    - '--name'
    - mybuilder
  - name: docker
    args:
    - docker
    - buildx
    - use
    - mybuilder
    id: select-builder
  - name: docker
    args:
    - docker
    - buildx
    - inspect
    - '--bootstrap'
    id: show-target-build-platforms
  - name: 'docker/compose:1.19.0'
    args: [ '-f', 'docker/docker-compose.yml', 'up', '-d' ]
  - name: 'maven:3-openjdk-11'
    entrypoint: 'mvn'
    args: [ 'install' ]
    env:
      - 'MONGO_HOST=mongo'
  - name: docker
    args:
    - docker
    - buildx
    - build
    - '--platform'
    - 'linux/amd64'
    - '-t'
    - 'eu.gcr.io/$PROJECT_ID/whakaoko'
    - '--push'
    - .
    id: build-multi-architecture-container-image
