version: '3'
services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
    - "27017:27017"
  memcached:
    image: memcached
    ports:
      - "11211:11211"
networks:
  default:
    external:
      name: cloudbuild